services:
  api:
    build:
      context: ./api
    environment:
      - NEO4J_URI=${NEO4J_URI-neo4j+s://demo.neo4jlabs.com}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD-recommendations}
      - NEO4J_USERNAME=${NEO4J_USERNAME-recommendations}
      - NEO4J_DATABASE=${NEO4J_DATABASE-recommendations}
      - OPENAI_API_KEY=${OPENAI_API_KEY-}
    networks:
      - net
    x-develop:
      watch:
        - action: rebuild
          path: ./api
    ports:
      - 8080:8080
  ui:
    build:
      context: ./ui
    networks:
      - net
    x-develop:
      watch:
        - action: rebuild
          path: ./ui
    ports:
      - 8501:8501
networks:
  net: